### PR TITLE
Add disable_inline_formatting option

### PR DESCRIPTION
**Pull request by michael-on-github**
Add an option `disable_inline_formatting` so that things like `<p>*sigh*</p>` do not get converted to `<p><strong>sigh</strong></p>`.

Usage:
```
my $textile = Text::Textile->new( disable_inline_formatting => 1 );
```

### CODE REVIEW

**Review by finn — APPROVED** [review]
LGTM!

**Review by finn — CHANGES_REQUESTED** [review]
Discussing changes.

**Comment by michael-on-github** [comment]
@finn oh, that's my indentation (mis)behaviour - I'm used to prefer tabs over spaces. Fixed!

**Review by finn — APPROVED** [review]
OK looks good!

**Comment by finn** [comment]
@mivanchenko can you please squash this down to one commit? Then we can merge. Also let's remove the reference to `BF-30715` from the commit message for the time being.

**Comment by michael-on-github** [comment]
Done

**Comment by michael-on-github** [comment]
All the tests including Andy's one [are passed](https://buzzfeed.atlassian.net/secure/attachment/91213/text-textile-2.13-add-option-passes.txt).

**Comment by finn** [comment]
@mivanchenko Great! Let's open a pull request against the upstream repo in bradchoate/text-textile and see if we can get this change integrated into the mainline as well.

**Comment by michael-on-github** [comment]
@finn when I had a look at the pull-request-to-be, I noticed we are going to reveal the following information about us: [`buzzfeed`, `mivanchenko` with my email address, and even a card number: `BF-30715`](https://github.com/bradchoate/text-textile/compare/master...buzzfeed:master).

On the other hand, I can do the pull request based on my personal fork, `mivanchenko/text-textile`, although I will have to delete my current repository `mivanchenko/text-textile` in order to refork it from `bradchoate/text-textile`, as it's currently forked from `buzzfeed/text-textile`, which still reveals the name `buzzfeed` on it.
Which way is better though?

Another thing, before I delete my repository `mivanchenko/text-textile`, is that operation going to be destructive for the merge already in place? I mean, is this pull request going to remain intact? Since this merge is based on my repo, it's a cross-repo merge.

**Comment by finn** [comment]
@mivanchenko this repo and pull request that we are discussing in is already public, so that is not a problem for this particular code change.

**Comment by finn** [comment]
> @mivanchenko this repo and pull request that we are discussing in is already public, so that is not a problem for this particular code change.

Do you want me to clean up the changes on master of this repo to exclude the issue information, etc.? That seems like it might be a cleaner approach.

**Comment by finn** [comment]
@mivanchenko ok I cleaned up master -- we can go ahead with this:

* https://github.com/bradchoate/text-textile/compare/master...buzzfeed:master

Note that the comparison is cleaner looking now.

**Comment by michael-on-github** [comment]
Yep - only one commit showing! [Here is the PR](https://github.com/bradchoate/text-textile/pull/23)

**Pull request merged**
